/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetCategory } from './budgetCategory';


export interface BudgetData { 
    /**
     * The month the budget data covers, formatted YYYY-MM
     */
    month?: string;
    /**
     * Total income for the month
     */
    income?: number;
    /**
     * Total expense spend for the month
     */
    spent?: number;
    /**
     * Income minus spent
     */
    net?: number;
    /**
     * Expense spend touching no budgeted category
     */
    untracked?: number;
    /**
     * Per-category budget vs. actual for the month
     */
    categories: Array<BudgetCategory>;
}

