/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BudgetCategory { 
    /**
     * Category foreign key
     */
    categoryId?: number;
    /**
     * Category name
     */
    name?: string;
    /**
     * Monthly budget target for the category
     */
    target?: number;
    /**
     * Amount spent against the category this month
     */
    spent?: number;
    /**
     * Whether spent exceeds target
     */
    over?: boolean;
}

