/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Category to relate receipts to
 */
export interface Category { 
    createdAt?: string;
    createdBy?: number;
    id?: number;
    /**
     * Name of the category
     */
    name?: string;
    /**
     * Description of the category
     */
    description?: string;
    /**
     * Whether receipts in this category count as income rather than spending.
     */
    isIncome?: boolean;
    /**
     * Hex color used for this category in charts (e.g.
     */
    color?: string;
    updatedAt?: string;
}

