/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A recurring monthly spend target for a single category within a single group
 */
export interface CategoryBudget { 
    id?: number;
    /**
     * Group foreign key
     */
    groupId?: number;
    /**
     * Category foreign key
     */
    categoryId?: number;
    /**
     * Monthly budget target amount for the category
     */
    amount?: string;
    createdAt?: string;
    updatedAt?: string;
}

