/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PieChartDataPoint { 
    /**
     * Label for the pie chart slice
     */
    label: string;
    /**
     * Value for the pie chart slice
     */
    value: number;
    /**
     * Hex color for the slice, from the category\'s stored color (empty for buckets without one)
     */
    color?: string;
}

