/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpsertWidgetCommand } from './upsertWidgetCommand';


export interface UpsertDashboardCommand { 
    /**
     * Dashboard name
     */
    name: string;
    /**
     * Group foreign key
     */
    groupId: string;
    /**
     * Widgets associated to dashboard
     */
    widgets?: Array<UpsertWidgetCommand>;
    /**
     * Dashboard-level date range preset (THIS_MONTH, LAST_MONTH, LAST_3_MONTHS, THIS_YEAR, ALL_TIME, CUSTOM)
     */
    period?: string;
    /**
     * ISO start date, used only when period is CUSTOM
     */
    periodStartDate?: string;
    /**
     * ISO end date, used only when period is CUSTOM
     */
    periodEndDate?: string;
}

