/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertCategoryCommand { 
    /**
     * Category id
     */
    id?: number;
    /**
     * Category name
     */
    name: string;
    /**
     * Category description
     */
    description?: string;
    /**
     * Whether receipts in this category count as income rather than spending.
     */
    isIncome?: boolean;
    /**
     * Hex color used for this category in charts (e.g.
     */
    color?: string;
}

